"""
Django settings for TesisImp project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""
import os
from pathlib import Path
import environ

env = environ.Env()
environ.Env.read_env()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#AGREGAR CLAVE AQUI
SECRET_KEY = env('SECRET_KEY_VALUE')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
#DEBUG = False

#ALLOWED_HOSTS = ['*']
ALLOWED_HOSTS = []

LOGOUT_REDIRECT_URL = '/'
LOGIN_REDIRECT_URL = 'AMCE:EstMisGrupos'
#Se define que se usará un modelo de usuario personalizado en la aplicación, esto para no tener errores de tipo Reverse accessor for
AUTH_USER_MODEL = 'AMCE.User'

#Ajustes para el envio de correos electrónicos
EMAIL_BACKEND = env('EMAIL_BACKEND_VALUE')
EMAIL_HOST = env('EMAIL_HOST_VALUE')
EMAIL_USE_TLS = env('EMAIL_USE_TLS_VALUE')
EMAIL_PORT = env('EMAIL_PORT_VALUE')
EMAIL_HOST_USER = env('EMAIL_HOST_USER_VALUE')
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD_VALUE')

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'crispy_forms',
    #local apps
    'AMCE',
    
]


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'whitenoise.middleware.WhiteNoiseMiddleware',
]

ROOT_URLCONF = 'TesisImp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'TesisImp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

'''
import dj_database_url
from decouple import config 
DATABASES = {
    'default': dj_database_url.config (
        default=config('DATABASE_URL')
    )
}
'''

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 9,
        }
    },
    {
        'NAME': 'AMCE.validators.MinimumLetterValidator',
    },
    {
        'NAME': 'AMCE.validators.MinimumNumberValidator',
    },
    {
        'NAME': 'AMCE.validators.MinimumCapitalaValidator',
    },
    {
        'NAME': 'AMCE.validators.MinimumSpecialCharactereValidator',
    }
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = 'America/Mexico_City'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#STATIC_URL = '/static/'

#STATICFILES_DIRS = (
 #   os.path.join(BASE_DIR, 'static'),
#)

#STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

DATE_INPUT_FORMATS = ('%d-%m-%Y','%Y-%m-%d')

PASSWORD_MINIMUM_ENTROPY = 35
